name: Chuck Norris Jokes Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create test accounts file
        run: |
          echo '{"1111-2222-3333": {"plan": "PRO"}}' > accounts.json

      - name: Run tests in Docker
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          services: |
            api
            redis

      - name: Run pytest with coverage
        run: |
          mkdir -p coverage
          docker compose run --rm -v $(pwd)/coverage:/code/coverage api pytest --cov=. --cov-report=xml:/code/coverage/coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        continue-on-error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./coverage/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: zeloras/chuck-norris-jokes
